### ISSUE TITLE
error in  android studio 

### ISSUE THREAD

**Issue by engr-erum** [frankiesardo/LinearListView#13]
i m using your lib in AS and have mentioned compile in gradle file too .  i have defined like this :                           compile 'com.github.frankiesardo:linearlistview:1.0.1@aar'
HERE IS THE ERROR I M GETTTING  
 java.lang.NoClassDefFoundError: com.linearlistview.R$attr   @frankiesardo

**Comment by engr-erum** [comment]
onCreateView
09-15 11:42:07.437  11970-11970/com..bcast W/dalvikvm﹕ method Lcom/linearlistview/internal/IcsLinearLayout;.drawDividersHorizontal incorrectly overrides package-private method with same name in Landroid/widget/LinearLayout;
09-15 11:42:07.437  11970-11970/com..bcast W/dalvikvm﹕ method Lcom/linearlistview/internal/IcsLinearLayout;.drawDividersVertical incorrectly overrides package-private method with same name in Landroid/widget/LinearLayout;
09-15 11:42:07.437  11970-11970/com.bcast W/dalvikvm﹕ method Lcom/linearlistview/internal/IcsLinearLayout;.drawHorizontalDivider incorrectly overrides package-private method with same name in Landroid/widget/LinearLayout;
09-15 11:42:07.437  11970-11970/com.bcast W/dalvikvm﹕ method Lcom/linearlistview/internal/IcsLinearLayout;.drawVerticalDivider incorrectly overrides package-private method with same name in Landroid/widget/LinearLayout;
09-15 11:42:07.437  11970-11970/com.bcast W/dalvikvm﹕ VFY: unable to resolve static field 16817 (dividerThickness) in Lcom/linearlistview/R$attr;
09-15 11:42:07.437  11970-11970/com.bcast D/dalvikvm﹕ VFY: replacing opcode 0x60 at 0x000a
09-15 11:42:07.437  11970-11970/com.bcast W/dalvikvm﹕ Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/linearlistview/LinearListView;
09-15 11:42:07.437  11970-11970/com.bcast W/dalvikvm﹕ Class init failed in Constructor.constructNative (Lcom/linearlistview/LinearListView;)
09-15 11:42:07.437  11970-11970/com.bcast D/AndroidRuntime﹕ Shutting down VM
09-15 11:42:07.437  11970-11970/com.bcast W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41817da0)
09-15 11:42:07.467  11970-11970/com.bcast E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.bcast, PID: 11970
    java.lang.NoClassDefFoundError: com.linearlistview.R$attr
            at com.linearlistview.LinearListView.<clinit>(LinearListView.java:24)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at com.bcast.ui.fragments.InfoFragment.onCreateView(InfoFragment.java:72)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
            at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:17437)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
            at android.view.View.measure(View.java:17437)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5381)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:17437)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5381)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:17437)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5381)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:17437)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5381)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:17437)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5381)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2586)
            at android.view.View.measure(View.java:17437)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2297)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1401)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1602)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1259)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6521)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
            at android.view.Choreographer.doCallbacks(Choreographer.java:613)
            at android.view.Choreographer.doFrame(Choreographer.java:583)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
    at @frankiesardo
