### ISSUE TITLE
error:NullPointerException

### ISSUE THREAD

**Issue by EzioL** [frankiesardo/LinearListView#15]

**Comment by ajans** [comment]
Do you refer to this NullPointerException in 1.0.1?

> ```
>               java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
>                   at android.view.ViewGroup$LayoutParams.<init>(ViewGroup.java:7040)
>                   at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7329)
>                   at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1962)
>                   at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1852)
>                   at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1846)
>                   at android.view.ViewGroup.addViewInner(ViewGroup.java:4463)
>                   at android.view.ViewGroup.addViewInLayout(ViewGroup.java:4430)
>                   at com.linearlistview.LinearListView.setupChildren(LinearListView.java:260)
>                   at com.linearlistview.LinearListView.setAdapter(LinearListView.java:129)
> ```

Then I have the same problem. The cause seems to lie in this setupchildren-method of LinearListView, where child.getLayoutParams() only returns null for the root-elements of the listitem-layout, which are inflated without being attached to a root-view:

`addViewInLayout(child, -1, child.getLayoutParams(), true);
`

**Comment by thalisvilela** [comment]
To fix this, i had to inflate the view informing the root view, without adding it to the parent, like this:
```
public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent) {
     convertView = LayoutInflater.from(context).inflate(R.layout.list_purchase_service_cell, parent, false);
     return convertView
}
```
